### ISSUE TITLE
блочные элементы внутри инлайновых - неприемлемо

### ISSUE THREAD

**Issue by panay** [ivancraze/online-shop#2]
https://github.com/ivancraze/online-shop/blob/a596f3ea68523a5b92fc66c6158222fa6fe60cd2/src/index.html#L25

да, в html5 внутрь тега `<a>` можно поместить блочный элемент, но в данной ситуации - это не требуется. Используй span, а параграфы (`<p></p>`) используй для параграфов.

**Comment by ivancraze** [comment]
Поправил, изменил на <span>
